improved flag handling

diff --git a/buildCommon b/buildCommon
--- a/buildCommon
+++ b/buildCommon
@@ -7,7 +7,7 @@ if [ ! "$1" ]; then
 	exit 1
 fi
 
-unset keep debug local nomore
+unset keep debug local nomore version
 while true; do
 
     case "$1" in
@@ -24,13 +24,17 @@ while true; do
             shift
             ;;
         *)
-            nomore=true
+            if [ "$version" ]; then
+                echo "I already caught $version for version string. Invalid flag: $1"
+                exit 1
+            fi
+            version="$1"
+            shift
             ;;
     esac
 
     [ "$nomore" ] && break
 done
-v="$1"
 
 if [ ! -f localConfig ]; then
 	echo "Make a localConfig out of localConfig.example before running this."
@@ -40,12 +44,12 @@ fi
 source localConfig || exit 1
 commonWeb="$web"
 
-if [ ! "$v" ]; then
-	echo "Missing v"
+if [ ! "$version" ]; then
+	echo "Missing version"
 	exit 1
 fi
 
-web="$web/$v"
+web="$web/$version"
 
 
 if [ ! "$code1" ]; then
@@ -53,7 +57,7 @@ if [ ! "$code1" ]; then
 	exit 1
 fi
 
-code="$code1/dcssca-$v/$code2"
+code="$code1/dcssca-$version/$code2"
 if [ "$local_code" ]; then
     code="$code1/dcssca/$code2"
 fi
@@ -61,7 +65,7 @@ fi
 if [ ! -d "$code" ]; then
     echo "Cloning repository..."
 	cd "$code1" || exit 1
-	git clone https://github.com/jeremygurr/dcssca.git -b "$v" "dcssca-$v" || exit 1
+	git clone https://github.com/jeremygurr/dcssca.git -b "$version" "dcssca-$version" || exit 1
 fi
 
 if [ ! -f "$code/contrib/sqlite/Makefile" ]; then
@@ -75,9 +79,9 @@ fi
 cd "$code" || exit 1
 
 if [ ! "$keep" -a ! "$local_code" ]; then
-	git checkout "$v" || exit 1
+	git checkout "$version" || exit 1
 	git pull || exit 1
-	git checkout "$v" || exit 1
+	git checkout "$version" || exit 1
 fi
 
 # usage: hydrate {from file} {to file}
