minor

diff --git a/buildDebug b/buildDebug
--- a/buildDebug
+++ b/buildDebug
@@ -2,7 +2,33 @@
 
 #make -j4 DEBUG_DIAGNOSTICS=t TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug
 
-make -j4 TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug-lite
-#make -j1 TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug-lite
 
+
+source common 
+
+unset success
+while true; do
+	mkdir -p $web/bin || break
+	touch $web/bin/crawl $web/bin/crawl.old
+	cd $web/bin || break
+	while true; do
+		rm crawl.old && break
+		echo "Failed, but will retry in a min..."
+		sleep 60
+	done
+	mv crawl crawl.old || break
+	cd $code || break
+
+    nice make -j4 TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug-lite
+
+	success=true
+    break
+done
+
+if [ "$success" ]; then
+	echo "Successful."
+else
+	echo "Failed!"
+	exit 1
+fi
 
