support multiple versions

diff --git a/common b/common
--- a/common
+++ b/common
@@ -2,12 +2,35 @@
 
 if [ ! "$commonSourced" ]; then
 
+if [ ! "$1" ]; then
+	echo "Usage: $0 {tag to update to}"
+	exit 1
+fi
+
 if [ ! -f localConfig ]; then
 	echo "Make a localConfig out of localConfig.example before running this."
 	exit 1
 fi
 
 source localConfig || exit 1
+
+if [ ! "$code1" ]; then
+	echo "Missing $code1"
+	exit 1
+fi
+
+code="$code1/dcssca-$v/$code2"
+
+if [ ! -d "$code" ]; then
+	cd "$code1" || exit 1
+	git clone https://github.com/jeremygurr/dcssca.git -b "$v" "dcssca-$v" || exit 1
+fi
+
+if [ ! -f "$code/contrib/sqlite/Makefile" ]; then
+	cd "$code" || exit 1
+	git submodule update --init || exit 1
+fi
+
 # usage: hydrate {from file} {to file}
 #   will replace variables in from file with values of variables defined in current shell environment
 unset hydrate
